pull_request_rules:
  - name: automatic merge when GitHub branch protection passes on main
    conditions:
      - base=main
    actions:
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge
